spring.application.name=tcbackend

## Database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=developer1
spring.datasource.password=PrograM123!

## Disable the default H2 database
spring.test.database.replace=none

## Log the SQL statements
logging.level.org.hibernate.SQL=DEBUG

## Log statements into multiple lines
spring.jpa.properties.hibernate.format_sql=true

## SQL statements highlighted in blue
spring.jpa.properties.hibernate.highlight_sql=true

## Log de parameters of sql statements
logging.level.org.hibernate.orm.jdbc.bind=TRACE

## DB naming convention
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl